### ISSUE TITLE
Song preview sometimes distort at song select

### ISSUE THREAD

**Issue by LonaGit** [Drewol/kson-rs#85]
Some song previews sometimes glitch out in the song select screen, slowing down and becoming very distorted.
Have listened to the audio files the preview is from, and those sound completely fine. Songs showcased in the video below always are distorted, but there are some songs that are fine, then gets distorted after you play them (in song select).
During actual play, everything sounds as it should.

Video link (google drive): [download](https://drive.google.com/file/d/1JCAr55c_wgoCwgIqfBWnnt9AMlQ8qHu1/view?usp=sharing) (23.1 MB)

**Comment by Drewol** [comment]
Which version of the game are you using?

**Comment by LonaGit** [comment]
where do i find the version number? cant seem to find it in-game.
either way, i am on the latest version the updater gives me

**Comment by Drewol** [comment]
since the game in this repository does not have an updater yet I assume you're playing on the C++ version from https://github.com/Drewol/unnamed-sdvx-clone and the issue should be opened there
